---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: airgradientdataserver
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airgradientdataserver
  template:
    metadata:
      labels:
        app: airgradientdataserver
    spec:
      containers:
        - name: airgradientdataserver
          image: 'scottbeca/airgradientdataserver:latest'
          ports:
            - containerPort: 5000
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '250m'
              memory: '256Mi'

---
kind: Service
apiVersion: v1
metadata:
  name: airgradientdataserver
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
  selector:
    app: airgradientdataserver
